/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use futures::{Future};
use reqwest;

use super::{Error, configuration};

pub struct ApplicationApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl ApplicationApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> ApplicationApiClient {
        ApplicationApiClient {
            configuration,
        }
    }
}

pub trait ApplicationApi {
    fn loriot_1_nwk_app_appid_app_delete(&self, APPID: &str) -> Box<dyn Future<Item = (), Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_app_get(&self, APPID: &str) -> Box<dyn Future<Item = crate::models::LoriotApplication, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_app_post(&self, APPID: &str, loriot_inline_object3: Option<crate::models::LoriotInlineObject3>) -> Box<dyn Future<Item = (), Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_capacity_post(&self, APPID: &str, loriot_inline_object5: crate::models::LoriotInlineObject5) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2004, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_last_data_get(&self, APPID: &str) -> Box<dyn Future<Item = Vec<crate::models::LoriotLastData>, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_log_get(&self, APPID: &str, page: f32, per_page: f32, filetype: Option<&str>, filter: Option<&str>, sort: Option<&str>) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2002, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_title_post(&self, APPID: &str, loriot_inline_object4: crate::models::LoriotInlineObject4) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2003, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_token_get(&self, APPID: &str) -> Box<dyn Future<Item = Vec<String>, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_token_post(&self, APPID: &str, body: serde_json::Value) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2006, Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_token_token_post(&self, APPID: &str, TOKEN: &str, body: serde_json::Value) -> Box<dyn Future<Item = (), Error = Error> + Send>;
    fn loriot_1_nwk_app_appid_traffic_freq_get(&self, APPID: &str, FREQ: &str) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2005, Error = Error> + Send>;
    fn loriot_1_nwk_apps_get(&self, page: f32, per_page: f32, filter: Option<&str>, sort: Option<&str>) -> Box<dyn Future<Item = crate::models::LoriotPaginationApps, Error = Error> + Send>;
    fn loriot_1_nwk_apps_post(&self, loriot_inline_object: Option<crate::models::LoriotInlineObject>) -> Box<dyn Future<Item = crate::models::LoriotApplication, Error = Error> + Send>;
    fn loriot_1_nwk_apps_usage_get(&self, ) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse200, Error = Error> + Send>;
}

impl ApplicationApi for ApplicationApiClient {
    fn loriot_1_nwk_app_appid_app_delete(&self, APPID: &str) -> Box<dyn Future<Item = (), Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/app", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.delete(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .map(|_| ())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_app_get(&self, APPID: &str) -> Box<dyn Future<Item = crate::models::LoriotApplication, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/app", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_app_post(&self, APPID: &str, loriot_inline_object3: Option<crate::models::LoriotInlineObject3>) -> Box<dyn Future<Item = (), Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/app", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&loriot_inline_object3);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .map(|_| ())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_capacity_post(&self, APPID: &str, loriot_inline_object5: crate::models::LoriotInlineObject5) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2004, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/capacity", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&loriot_inline_object5);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_last_data_get(&self, APPID: &str) -> Box<dyn Future<Item = Vec<crate::models::LoriotLastData>, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/last_data", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_log_get(&self, APPID: &str, page: f32, per_page: f32, filetype: Option<&str>, filter: Option<&str>, sort: Option<&str>) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2002, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/log", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref s) = filetype {
            req_builder = req_builder.query(&[("filetype", &s.to_string())]);
        }
        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("perPage", &per_page.to_string())]);
        if let Some(ref s) = filter {
            req_builder = req_builder.query(&[("filter", &s.to_string())]);
        }
        if let Some(ref s) = sort {
            req_builder = req_builder.query(&[("sort", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_title_post(&self, APPID: &str, loriot_inline_object4: crate::models::LoriotInlineObject4) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2003, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/title", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&loriot_inline_object4);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_token_get(&self, APPID: &str) -> Box<dyn Future<Item = Vec<String>, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/token", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_token_post(&self, APPID: &str, body: serde_json::Value) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2006, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/token", configuration.base_path, APPID=crate::apis::urlencode(APPID));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&body);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_token_token_post(&self, APPID: &str, TOKEN: &str, body: serde_json::Value) -> Box<dyn Future<Item = (), Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/token/{TOKEN}", configuration.base_path, APPID=crate::apis::urlencode(APPID), TOKEN=crate::apis::urlencode(TOKEN));
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&body);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .map(|_| ())
            .from_err()
        )
    }

    fn loriot_1_nwk_app_appid_traffic_freq_get(&self, APPID: &str, FREQ: &str) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse2005, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/app/{APPID}/traffic_{FREQ}", configuration.base_path, APPID=crate::apis::urlencode(APPID), FREQ=crate::apis::urlencode(FREQ));
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_apps_get(&self, page: f32, per_page: f32, filter: Option<&str>, sort: Option<&str>) -> Box<dyn Future<Item = crate::models::LoriotPaginationApps, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/apps", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        req_builder = req_builder.query(&[("page", &page.to_string())]);
        req_builder = req_builder.query(&[("perPage", &per_page.to_string())]);
        if let Some(ref s) = filter {
            req_builder = req_builder.query(&[("filter", &s.to_string())]);
        }
        if let Some(ref s) = sort {
            req_builder = req_builder.query(&[("sort", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_apps_post(&self, loriot_inline_object: Option<crate::models::LoriotInlineObject>) -> Box<dyn Future<Item = crate::models::LoriotApplication, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/apps", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };
        req_builder = req_builder.json(&loriot_inline_object);

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

    fn loriot_1_nwk_apps_usage_get(&self, ) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse200, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/apps/usage", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

}
