/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;
use futures::{Future};
use reqwest;

use super::{Error, configuration};

pub struct SystemApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl SystemApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> SystemApiClient {
        SystemApiClient {
            configuration,
        }
    }
}

pub trait SystemApi {
    fn loriot_1_nwk_status_get(&self, ) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse20024, Error = Error> + Send>;
}

impl SystemApi for SystemApiClient {
    fn loriot_1_nwk_status_get(&self, ) -> Box<dyn Future<Item = crate::models::LoriotInlineResponse20024, Error = Error> + Send> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/1/nwk/status", configuration.base_path);
        let mut req_builder = client.get(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        if let Some(ref token) = configuration.bearer_access_token {
            req_builder = req_builder.bearer_auth(token.to_owned());
        };
        if let Some(ref apikey) = configuration.api_key {
            let key = apikey.key.clone();
            let val = match apikey.prefix {
                Some(ref prefix) => format!("{} {}", prefix, key),
                None => key,
            };
            req_builder = req_builder.header("Authorization", val);
        };

        // send request
        Box::new(req_builder.send()
            .and_then(|i| i.error_for_status())
            .and_then(|mut i| i.json())
            .from_err()
        )
    }

}
