/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse200 {
    /// number of applications used
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<f32>,
    /// Sum of device capacity between all applications
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<f32>,
    /// multicast capacity
    #[serde(rename = "mcastCapacity", skip_serializing_if = "Option::is_none")]
    pub mcast_capacity: Option<f32>,
    /// multicast used
    #[serde(rename = "mcastUsed", skip_serializing_if = "Option::is_none")]
    pub mcast_used: Option<f32>,
    /// devices in use between all applications
    #[serde(rename = "used", skip_serializing_if = "Option::is_none")]
    pub used: Option<f32>,
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<serde_json::Value>,
}

impl LoriotInlineResponse200 {
    pub fn new() -> LoriotInlineResponse200 {
        LoriotInlineResponse200 {
            apps: None,
            capacity: None,
            mcast_capacity: None,
            mcast_used: None,
            used: None,
            _id: None,
        }
    }
}


