/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Loriot1NwkAppAppidDeviceDeveuiRadioFreqGws {
    /// number of frames downlink
    #[serde(rename = "dnfcn", skip_serializing_if = "Option::is_none")]
    pub dnfcn: Option<f32>,
    /// number of frames uplink
    #[serde(rename = "fcn", skip_serializing_if = "Option::is_none")]
    pub fcn: Option<f32>,
    /// gateway identifier
    #[serde(rename = "gweui", skip_serializing_if = "Option::is_none")]
    pub gweui: Option<String>,
    /// number of lost frames
    #[serde(rename = "lst", skip_serializing_if = "Option::is_none")]
    pub lst: Option<f32>,
    /// signal strength in dBm
    #[serde(rename = "rssi", skip_serializing_if = "Option::is_none")]
    pub rssi: Option<f32>,
    /// signal-to-noise ratio in dB
    #[serde(rename = "snr", skip_serializing_if = "Option::is_none")]
    pub snr: Option<f32>,
}

impl Loriot1NwkAppAppidDeviceDeveuiRadioFreqGws {
    pub fn new() -> Loriot1NwkAppAppidDeviceDeveuiRadioFreqGws {
        Loriot1NwkAppAppidDeviceDeveuiRadioFreqGws {
            dnfcn: None,
            fcn: None,
            gweui: None,
            lst: None,
            rssi: None,
            snr: None,
        }
    }
}


