/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject13 {
    /// Numeric values from 0 (unlimited) to 255 (device disabled).
    #[serde(rename = "dutycycle", skip_serializing_if = "Option::is_none")]
    pub dutycycle: Option<f32>,
}

impl LoriotInlineObject13 {
    pub fn new() -> LoriotInlineObject13 {
        LoriotInlineObject13 {
            dutycycle: None,
        }
    }
}


