/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoriotInlineResponse20021Metadata : Log metadata properties



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20021Metadata {
    /// gateway identifier
    #[serde(rename = "gweui", skip_serializing_if = "Option::is_none")]
    pub gweui: Option<String>,
    /// server instance
    #[serde(rename = "instance", skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
}

impl LoriotInlineResponse20021Metadata {
    /// Log metadata properties
    pub fn new() -> LoriotInlineResponse20021Metadata {
        LoriotInlineResponse20021Metadata {
            gweui: None,
            instance: None,
        }
    }
}


