/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotLocation {
    /// Gateway address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Gateway city
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Gateway ZIP
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    /// ISO country code
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Gateway GPS latituted for offline installations
    #[serde(rename = "lat")]
    pub lat: f32,
    /// Gateway GPS longitude for offline installations
    #[serde(rename = "lon")]
    pub lon: f32,
    /// Chinese address
    #[serde(rename = "baidu", skip_serializing_if = "Option::is_none")]
    pub baidu: Option<String>,
}

impl LoriotLocation {
    pub fn new(lat: f32, lon: f32) -> LoriotLocation {
        LoriotLocation {
            address: None,
            city: None,
            zip: None,
            country: None,
            lat,
            lon,
            baidu: None,
        }
    }
}


