/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject1 {
    #[serde(rename = "osetup", skip_serializing_if = "Option::is_none")]
    pub osetup: Option<crate::models::Loriot1NwkAppAppidOutputsOsetup>,
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
}

impl LoriotInlineObject1 {
    pub fn new() -> LoriotInlineObject1 {
        LoriotInlineObject1 {
            osetup: None,
            output: None,
        }
    }
}


