/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20017 {
    /// Midnight date from server local time
    #[serde(rename = "midnight", skip_serializing_if = "Option::is_none")]
    pub midnight: Option<String>,
    #[serde(rename = "traffic", skip_serializing_if = "Option::is_none")]
    pub traffic: Option<Vec<crate::models::LoriotInlineResponse20017Traffic>>,
}

impl LoriotInlineResponse20017 {
    pub fn new() -> LoriotInlineResponse20017 {
        LoriotInlineResponse20017 {
            midnight: None,
            traffic: None,
        }
    }
}


