/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotOutputDetail {
    /// Detail information in HTML
    #[serde(rename = "howto", skip_serializing_if = "Option::is_none")]
    pub howto: Option<String>,
    /// local or third party
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Output mechanism
    #[serde(rename = "mech", skip_serializing_if = "Option::is_none")]
    pub mech: Option<String>,
    /// output title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// output identifier
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "form", skip_serializing_if = "Option::is_none")]
    pub form: Option<crate::models::LoriotOutputDetailForm>,
}

impl LoriotOutputDetail {
    pub fn new() -> LoriotOutputDetail {
        LoriotOutputDetail {
            howto: None,
            location: None,
            mech: None,
            title: None,
            _id: None,
            form: None,
        }
    }
}


