/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoriotInlineObject22 : New visibility value



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject22 {
    /// Resource visibility to other members of user's organization
    #[serde(rename = "visibility")]
    pub visibility: LoriotVisibility,
}

impl LoriotInlineObject22 {
    /// New visibility value
    pub fn new(visibility: LoriotVisibility) -> LoriotInlineObject22 {
        LoriotInlineObject22 {
            visibility,
        }
    }
}

/// Resource visibility to other members of user's organization
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum LoriotVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
}

