/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse204 {
    /// Alerts configuration
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<bool>,
}

impl LoriotInlineResponse204 {
    pub fn new() -> LoriotInlineResponse204 {
        LoriotInlineResponse204 {
            alerts: None,
        }
    }
}


