/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20016 {
    /// Count gateway networks
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<f32>,
}

impl LoriotInlineResponse20016 {
    pub fn new() -> LoriotInlineResponse20016 {
        LoriotInlineResponse20016 {
            count: None,
        }
    }
}


