/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Loriot1NwkGatewayGweuiSysinfoStorage {
    /// free storage memory
    #[serde(rename = "free", skip_serializing_if = "Option::is_none")]
    pub free: Option<f32>,
    /// total storage memory
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f32>,
    /// folder on witch stat has been done
    #[serde(rename = "folder", skip_serializing_if = "Option::is_none")]
    pub folder: Option<String>,
}

impl Loriot1NwkGatewayGweuiSysinfoStorage {
    pub fn new() -> Loriot1NwkGatewayGweuiSysinfoStorage {
        Loriot1NwkGatewayGweuiSysinfoStorage {
            free: None,
            size: None,
            folder: None,
        }
    }
}


