/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject19 {
    /// New user email
    #[serde(rename = "email")]
    pub email: String,
}

impl LoriotInlineObject19 {
    pub fn new(email: String) -> LoriotInlineObject19 {
        LoriotInlineObject19 {
            email,
        }
    }
}


