/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20021Events {
    /// Log date
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
    /// Severity enumeration value
    #[serde(rename = "sev", skip_serializing_if = "Option::is_none")]
    pub sev: Option<f32>,
    /// Log source ID
    #[serde(rename = "src", skip_serializing_if = "Option::is_none")]
    pub src: Option<String>,
    /// Log event name
    #[serde(rename = "evt", skip_serializing_if = "Option::is_none")]
    pub evt: Option<String>,
    /// Log message
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<crate::models::LoriotInlineResponse20021Metadata>,
}

impl LoriotInlineResponse20021Events {
    pub fn new() -> LoriotInlineResponse20021Events {
        LoriotInlineResponse20021Events {
            ts: None,
            sev: None,
            src: None,
            evt: None,
            msg: None,
            metadata: None,
        }
    }
}


