/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse2004 {
    /// decrement capacity (multiples of 10)
    #[serde(rename = "dec", skip_serializing_if = "Option::is_none")]
    pub dec: Option<f32>,
    /// increment capacity (multiples of 10)
    #[serde(rename = "inc", skip_serializing_if = "Option::is_none")]
    pub inc: Option<f32>,
}

impl LoriotInlineResponse2004 {
    pub fn new() -> LoriotInlineResponse2004 {
        LoriotInlineResponse2004 {
            dec: None,
            inc: None,
        }
    }
}


