/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20010 {
    /// Application Session Key
    #[serde(rename = "appskey", skip_serializing_if = "Option::is_none")]
    pub appskey: Option<String>,
}

impl LoriotInlineResponse20010 {
    pub fn new() -> LoriotInlineResponse20010 {
        LoriotInlineResponse20010 {
            appskey: None,
        }
    }
}


