/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20021SatList {
    /// SV PRN number
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f32>,
    /// Elevation, in degrees, 90° maximum
    #[serde(rename = "ele", skip_serializing_if = "Option::is_none")]
    pub ele: Option<f32>,
    /// Azimuth, degrees from True North, 000° through 359°
    #[serde(rename = "azi", skip_serializing_if = "Option::is_none")]
    pub azi: Option<f32>,
    /// SNR, 00 through 99 dB (null when not tracking)
    #[serde(rename = "snr", skip_serializing_if = "Option::is_none")]
    pub snr: Option<f32>,
}

impl LoriotInlineResponse20021SatList {
    pub fn new() -> LoriotInlineResponse20021SatList {
        LoriotInlineResponse20021SatList {
            id: None,
            ele: None,
            azi: None,
            snr: None,
        }
    }
}


