/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20022 {
    /// The amount of alerts
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<Vec<crate::models::LoriotInlineResponse20022Alerts>>,
}

impl LoriotInlineResponse20022 {
    pub fn new() -> LoriotInlineResponse20022 {
        LoriotInlineResponse20022 {
            total: None,
            alerts: None,
        }
    }
}


