/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse2002 {
    /// The amount of registers in the response
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<crate::models::LoriotInlineResponse2002Events>>,
}

impl LoriotInlineResponse2002 {
    pub fn new() -> LoriotInlineResponse2002 {
        LoriotInlineResponse2002 {
            total: None,
            events: None,
        }
    }
}


