/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse2009 {
    /// Application Key (Device Key)
    #[serde(rename = "appkey", skip_serializing_if = "Option::is_none")]
    pub appkey: Option<String>,
}

impl LoriotInlineResponse2009 {
    pub fn new() -> LoriotInlineResponse2009 {
        LoriotInlineResponse2009 {
            appkey: None,
        }
    }
}


