/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Loriot1NwkGatewayGweuiTrackFiles {
    /// Enable track gateway files
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Enable to track default files declared in gateway model
    #[serde(rename = "useGatewayModelList", skip_serializing_if = "Option::is_none")]
    pub use_gateway_model_list: Option<bool>,
    /// Custom list of files to track in the gateway
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<crate::models::Loriot1NwkGatewayGweuiTrackFilesFiles>>,
}

impl Loriot1NwkGatewayGweuiTrackFiles {
    pub fn new() -> Loriot1NwkGatewayGweuiTrackFiles {
        Loriot1NwkGatewayGweuiTrackFiles {
            enabled: None,
            use_gateway_model_list: None,
            files: None,
        }
    }
}


