/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20011 {
    /// Number of apps in use
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<f32>,
    /// Number of signed devices
    #[serde(rename = "devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<f32>,
    /// Max amount of devices
    #[serde(rename = "devlimit", skip_serializing_if = "Option::is_none")]
    pub devlimit: Option<f32>,
    /// Number of devices in use
    #[serde(rename = "devuse", skip_serializing_if = "Option::is_none")]
    pub devuse: Option<f32>,
    /// Gateways in use
    #[serde(rename = "gateways", skip_serializing_if = "Option::is_none")]
    pub gateways: Option<f32>,
    /// Limit of gateways in account
    #[serde(rename = "gwlimit", skip_serializing_if = "Option::is_none")]
    pub gwlimit: Option<f32>,
    /// Limit of multicast devices in account
    #[serde(rename = "mcastdevices", skip_serializing_if = "Option::is_none")]
    pub mcastdevices: Option<f32>,
    /// Multicast devices in use
    #[serde(rename = "mcastdevuse", skip_serializing_if = "Option::is_none")]
    pub mcastdevuse: Option<f32>,
}

impl LoriotInlineResponse20011 {
    pub fn new() -> LoriotInlineResponse20011 {
        LoriotInlineResponse20011 {
            apps: None,
            devices: None,
            devlimit: None,
            devuse: None,
            gateways: None,
            gwlimit: None,
            mcastdevices: None,
            mcastdevuse: None,
        }
    }
}


