/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse2006 {
    /// secret token shared
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

impl LoriotInlineResponse2006 {
    pub fn new() -> LoriotInlineResponse2006 {
        LoriotInlineResponse2006 {
            token: None,
        }
    }
}


