/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotDeviceMacCommandPaged {
    #[serde(rename = "macCommands", skip_serializing_if = "Option::is_none")]
    pub mac_commands: Option<Vec<crate::models::LoriotDeviceMacCommandPagedMacCommands>>,
    /// number of MAC commands found
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
}

impl LoriotDeviceMacCommandPaged {
    pub fn new() -> LoriotDeviceMacCommandPaged {
        LoriotDeviceMacCommandPaged {
            mac_commands: None,
            total: None,
        }
    }
}


