/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoriotInlineObject20 : Gateway to register and add it to current gateway network



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject20 {
    /// base / manufacturer of the gateway
    #[serde(rename = "base")]
    pub base: String,
    /// model of the gateway
    #[serde(rename = "model")]
    pub model: String,
    /// Gateway MAC
    #[serde(rename = "MAC")]
    pub MAC: String,
    /// bus used to connect the concentrator
    #[serde(rename = "bus")]
    pub bus: String,
    /// model of the concentrator
    #[serde(rename = "concentrator")]
    pub concentrator: String,
    #[serde(rename = "card")]
    pub card: f32,
    #[serde(rename = "location")]
    pub location: crate::models::LoriotLocation,
}

impl LoriotInlineObject20 {
    /// Gateway to register and add it to current gateway network
    pub fn new(base: String, model: String, MAC: String, bus: String, concentrator: String, card: f32, location: crate::models::LoriotLocation) -> LoriotInlineObject20 {
        LoriotInlineObject20 {
            base,
            model,
            MAC,
            bus,
            concentrator,
            card,
            location,
        }
    }
}


