/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20023Alerts {
    /// Alert creation date
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
    /// Alert identifier
    #[serde(rename = "alertId", skip_serializing_if = "Option::is_none")]
    pub alert_id: Option<f32>,
    /// Alert message sent
    #[serde(rename = "alert", skip_serializing_if = "Option::is_none")]
    pub alert: Option<String>,
    /// Alert acknowledgement status
    #[serde(rename = "seen", skip_serializing_if = "Option::is_none")]
    pub seen: Option<bool>,
}

impl LoriotInlineResponse20023Alerts {
    pub fn new() -> LoriotInlineResponse20023Alerts {
        LoriotInlineResponse20023Alerts {
            ts: None,
            alert_id: None,
            alert: None,
            seen: None,
        }
    }
}


