/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20026 {
    /// bandwith
    #[serde(rename = "bw", skip_serializing_if = "Option::is_none")]
    pub bw: Option<f32>,
    /// frequency
    #[serde(rename = "freq", skip_serializing_if = "Option::is_none")]
    pub freq: Option<f32>,
    /// mode
    #[serde(rename = "mod", skip_serializing_if = "Option::is_none")]
    pub _mod: Option<String>,
    /// radio configuration
    #[serde(rename = "radio", skip_serializing_if = "Option::is_none")]
    pub radio: Option<f32>,
    #[serde(rename = "rx2", skip_serializing_if = "Option::is_none")]
    pub rx2: Option<crate::models::Loriot1NwkChannelplansLoragwversionBandnameChannelsRx2>,
}

impl LoriotInlineResponse20026 {
    pub fn new() -> LoriotInlineResponse20026 {
        LoriotInlineResponse20026 {
            bw: None,
            freq: None,
            _mod: None,
            radio: None,
            rx2: None,
        }
    }
}


