/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20012 {
    /// Amount of gateways for current network
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "gateways", skip_serializing_if = "Option::is_none")]
    pub gateways: Option<Vec<crate::models::LoriotGateway>>,
}

impl LoriotInlineResponse20012 {
    pub fn new() -> LoriotInlineResponse20012 {
        LoriotInlineResponse20012 {
            total: None,
            gateways: None,
        }
    }
}


