/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20021Gps {
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// latitude decimal
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f32>,
    /// longitude decimal
    #[serde(rename = "lon", skip_serializing_if = "Option::is_none")]
    pub lon: Option<f32>,
    /// altitude (meters)
    #[serde(rename = "alt", skip_serializing_if = "Option::is_none")]
    pub alt: Option<f32>,
    /// index in 'satList'
    #[serde(rename = "satUsed", skip_serializing_if = "Option::is_none")]
    pub sat_used: Option<f32>,
    #[serde(rename = "satList", skip_serializing_if = "Option::is_none")]
    pub sat_list: Option<Vec<crate::models::LoriotInlineResponse20021SatList>>,
}

impl LoriotInlineResponse20021Gps {
    pub fn new() -> LoriotInlineResponse20021Gps {
        LoriotInlineResponse20021Gps {
            date: None,
            lat: None,
            lon: None,
            alt: None,
            sat_used: None,
            sat_list: None,
        }
    }
}


