/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20014 {
    /// Amount of networks for current user
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Vec<crate::models::LoriotGatewayNetwork>>,
}

impl LoriotInlineResponse20014 {
    pub fn new() -> LoriotInlineResponse20014 {
        LoriotInlineResponse20014 {
            total: None,
            networks: None,
        }
    }
}


