/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotDeviceMacCommandPagedMacCommands {
    /// MAC command name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// MAC command sent/received date
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// MAC command raw frame options
    #[serde(rename = "frameOptions", skip_serializing_if = "Option::is_none")]
    pub frame_options: Option<String>,
    /// MAC command sanitized frame options
    #[serde(rename = "sanitizedFrameOptions", skip_serializing_if = "Option::is_none")]
    pub sanitized_frame_options: Option<serde_json::Value>,
}

impl LoriotDeviceMacCommandPagedMacCommands {
    pub fn new() -> LoriotDeviceMacCommandPagedMacCommands {
        LoriotDeviceMacCommandPagedMacCommands {
            name: None,
            date: None,
            frame_options: None,
            sanitized_frame_options: None,
        }
    }
}


