/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Loriot1NwkGatewayGweuiTrackFilesFiles {
    /// Full path of file to track
    #[serde(rename = "filePath", skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    /// Amount of time between each file read (seconds)
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<f32>,
}

impl Loriot1NwkGatewayGweuiTrackFilesFiles {
    pub fn new() -> Loriot1NwkGatewayGweuiTrackFilesFiles {
        Loriot1NwkGatewayGweuiTrackFilesFiles {
            file_path: None,
            interval: None,
        }
    }
}


