/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotUpDownLink {
    #[serde(rename = "noPayload", skip_serializing_if = "Option::is_none")]
    pub no_payload: Option<crate::models::LoriotUpDownLinkNoPayload>,
    #[serde(rename = "payload", skip_serializing_if = "Option::is_none")]
    pub payload: Option<crate::models::LoriotUpDownLinkNoPayload>,
}

impl LoriotUpDownLink {
    pub fn new() -> LoriotUpDownLink {
        LoriotUpDownLink {
            no_payload: None,
            payload: None,
        }
    }
}


