/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20018 {
    /// date time
    #[serde(rename = "midnight", skip_serializing_if = "Option::is_none")]
    pub midnight: Option<String>,
    /// total uptime
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<f32>,
    #[serde(rename = "uptime", skip_serializing_if = "Option::is_none")]
    pub uptime: Option<Vec<crate::models::LoriotInlineResponse20018Uptime>>,
}

impl LoriotInlineResponse20018 {
    pub fn new() -> LoriotInlineResponse20018 {
        LoriotInlineResponse20018 {
            midnight: None,
            sum: None,
            uptime: None,
        }
    }
}


