/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject {
    /// Application title
    #[serde(rename = "title")]
    pub title: String,
    /// Maximum amount of devices to register in the application
    #[serde(rename = "capacity")]
    pub capacity: f32,
    /// Resource visibility to other members of user's organization
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<LoriotVisibility>,
}

impl LoriotInlineObject {
    pub fn new(title: String, capacity: f32) -> LoriotInlineObject {
        LoriotInlineObject {
            title,
            capacity,
            visibility: None,
        }
    }
}

/// Resource visibility to other members of user's organization
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum LoriotVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
}

