/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotTierFeatures {
    /// Informative field for web usage
    #[serde(rename = "0", skip_serializing_if = "Option::is_none")]
    pub var_0: Option<String>,
    /// Informative field for web usage
    #[serde(rename = "1", skip_serializing_if = "Option::is_none")]
    pub var_1: Option<String>,
    /// Informative field for web usage
    #[serde(rename = "2", skip_serializing_if = "Option::is_none")]
    pub var_2: Option<String>,
}

impl LoriotTierFeatures {
    pub fn new() -> LoriotTierFeatures {
        LoriotTierFeatures {
            var_0: None,
            var_1: None,
            var_2: None,
        }
    }
}


