/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject12 {
    /// AES128 Key
    #[serde(rename = "appskey", skip_serializing_if = "Option::is_none")]
    pub appskey: Option<String>,
}

impl LoriotInlineObject12 {
    pub fn new() -> LoriotInlineObject12 {
        LoriotInlineObject12 {
            appskey: None,
        }
    }
}


