/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotMcast {
    /// Multicast device EUI identifier (hexadecimal)
    #[serde(rename = "mcasteui")]
    pub mcasteui: String,
    /// Multicast devaddr
    #[serde(rename = "devaddr")]
    pub devaddr: String,
    /// Frequency to be used for downlink
    #[serde(rename = "freq")]
    pub freq: f32,
    /// datarate
    #[serde(rename = "datr")]
    pub datr: String,
    /// application session key
    #[serde(rename = "appskey")]
    pub appskey: String,
    /// network server key
    #[serde(rename = "nwkskey")]
    pub nwkskey: String,
    /// Time in advance to send multicast downlink to gateway (milliseconds).
    #[serde(rename = "preload")]
    pub preload: f32,
    /// downlink sequence number
    #[serde(rename = "seqdn")]
    pub seqdn: f32,
}

impl LoriotMcast {
    pub fn new(mcasteui: String, devaddr: String, freq: f32, datr: String, appskey: String, nwkskey: String, preload: f32, seqdn: f32) -> LoriotMcast {
        LoriotMcast {
            mcasteui,
            devaddr,
            freq,
            datr,
            appskey,
            nwkskey,
            preload,
            seqdn,
        }
    }
}


