/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject5 {
    #[serde(rename = "dec", skip_serializing_if = "Option::is_none")]
    pub dec: Option<f32>,
}

impl LoriotInlineObject5 {
    pub fn new() -> LoriotInlineObject5 {
        LoriotInlineObject5 {
            dec: None,
        }
    }
}


