/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20021 {
    /// The amount of GPS values by filter used
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "gps", skip_serializing_if = "Option::is_none")]
    pub gps: Option<Vec<crate::models::LoriotInlineResponse20021Gps>>,
}

impl LoriotInlineResponse20021 {
    pub fn new() -> LoriotInlineResponse20021 {
        LoriotInlineResponse20021 {
            total: None,
            gps: None,
        }
    }
}


