/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoriotInlineObject23 : New Gateway Network to register



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject23 {
    /// custom Gateway Network title name
    #[serde(rename = "name")]
    pub name: String,
    /// Gateway address
    #[serde(rename = "address")]
    pub address: String,
    /// Gateway city
    #[serde(rename = "city")]
    pub city: String,
    /// Gateway ZIP
    #[serde(rename = "zip")]
    pub zip: String,
    /// ISO country code
    #[serde(rename = "country")]
    pub country: String,
    /// Chinese address
    #[serde(rename = "baidu", skip_serializing_if = "Option::is_none")]
    pub baidu: Option<String>,
    /// Custom gateway GPS lat (bypass back-end location lookup)
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f32>,
    /// Custom gateway GPS lon (bypass back-end location lookup)
    #[serde(rename = "lon", skip_serializing_if = "Option::is_none")]
    pub lon: Option<f32>,
    /// Resource visibility to other members of user's organization
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<LoriotVisibility>,
}

impl LoriotInlineObject23 {
    /// New Gateway Network to register
    pub fn new(name: String, address: String, city: String, zip: String, country: String) -> LoriotInlineObject23 {
        LoriotInlineObject23 {
            name,
            address,
            city,
            zip,
            country,
            baidu: None,
            lat: None,
            lon: None,
            visibility: None,
        }
    }
}

/// Resource visibility to other members of user's organization
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum LoriotVisibility {
    #[serde(rename = "public")]
    Public,
    #[serde(rename = "private")]
    Private,
}

