/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse20015 {
    /// Page number for the pagination response
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<f32>,
    /// Amount of applications to retrieve per page
    #[serde(rename = "perPage", skip_serializing_if = "Option::is_none")]
    pub per_page: Option<f32>,
    /// Amount of applications to iterate using pagination
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
    #[serde(rename = "apps", skip_serializing_if = "Option::is_none")]
    pub apps: Option<Vec<crate::models::LoriotGateway>>,
}

impl LoriotInlineResponse20015 {
    pub fn new() -> LoriotInlineResponse20015 {
        LoriotInlineResponse20015 {
            page: None,
            per_page: None,
            total: None,
            apps: None,
        }
    }
}


