/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotLastDataDevice {
    /// acknowledgement
    #[serde(rename = "ack", skip_serializing_if = "Option::is_none")]
    pub ack: Option<bool>,
    /// battery (0 to 255)
    #[serde(rename = "bat", skip_serializing_if = "Option::is_none")]
    pub bat: Option<f32>,
    /// last command
    #[serde(rename = "cmd", skip_serializing_if = "Option::is_none")]
    pub cmd: Option<String>,
    /// last data received
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<String>,
    /// datarate
    #[serde(rename = "dr", skip_serializing_if = "Option::is_none")]
    pub dr: Option<String>,
    /// framecounter
    #[serde(rename = "fcnt", skip_serializing_if = "Option::is_none")]
    pub fcnt: Option<f32>,
    /// frequency
    #[serde(rename = "freq", skip_serializing_if = "Option::is_none")]
    pub freq: Option<f32>,
    /// comunication port
    #[serde(rename = "port", skip_serializing_if = "Option::is_none")]
    pub port: Option<f32>,
    /// downlink sequence number
    #[serde(rename = "seqno", skip_serializing_if = "Option::is_none")]
    pub seqno: Option<f32>,
    /// Session key ID
    #[serde(rename = "sessionKeyId", skip_serializing_if = "Option::is_none")]
    pub session_key_id: Option<String>,
    /// time on air
    #[serde(rename = "toa", skip_serializing_if = "Option::is_none")]
    pub toa: Option<f32>,
    /// timestamp
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<f32>,
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    #[serde(rename = "gws", skip_serializing_if = "Option::is_none")]
    pub gws: Option<Vec<crate::models::LoriotLastDataDeviceGws>>,
}

impl LoriotLastDataDevice {
    pub fn new() -> LoriotLastDataDevice {
        LoriotLastDataDevice {
            ack: None,
            bat: None,
            cmd: None,
            data: None,
            dr: None,
            fcnt: None,
            freq: None,
            port: None,
            seqno: None,
            session_key_id: None,
            toa: None,
            ts: None,
            _id: None,
            gws: None,
        }
    }
}


