/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotLastDataDeviceGws {
    /// Received Signal Strength Indicator
    #[serde(rename = "rssi", skip_serializing_if = "Option::is_none")]
    pub rssi: Option<f32>,
    /// signal noise ratio
    #[serde(rename = "snr", skip_serializing_if = "Option::is_none")]
    pub snr: Option<f32>,
    /// timestamp
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<f32>,
    /// GPS time in milliseconds
    #[serde(rename = "tmms", skip_serializing_if = "Option::is_none")]
    pub tmms: Option<f32>,
    /// date and time
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
}

impl LoriotLastDataDeviceGws {
    pub fn new() -> LoriotLastDataDeviceGws {
        LoriotLastDataDeviceGws {
            rssi: None,
            snr: None,
            ts: None,
            tmms: None,
            time: None,
        }
    }
}


