/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotGatewayNetwork {
    /// Gateway Network roaming ID
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<f32>,
    /// Gateway Network creation date
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// custom Gateway Network title name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Gateway address
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    /// Gateway city
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
    /// Gateway ZIP
    #[serde(rename = "zip", skip_serializing_if = "Option::is_none")]
    pub zip: Option<String>,
    /// ISO country code
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Gateway GPS lat
    #[serde(rename = "lat", skip_serializing_if = "Option::is_none")]
    pub lat: Option<f32>,
    /// Gateway GPS lon
    #[serde(rename = "lon", skip_serializing_if = "Option::is_none")]
    pub lon: Option<f32>,
    /// Amount of gateways registered in network
    #[serde(rename = "gateways", skip_serializing_if = "Option::is_none")]
    pub gateways: Option<f32>,
    /// set the visibility of the network. \"Vivible only to me\" or \"Visible to all organization users\"
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<String>,
}

impl LoriotGatewayNetwork {
    pub fn new() -> LoriotGatewayNetwork {
        LoriotGatewayNetwork {
            _id: None,
            created_at: None,
            name: None,
            address: None,
            city: None,
            zip: None,
            country: None,
            lat: None,
            lon: None,
            gateways: None,
            visibility: None,
        }
    }
}


