/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject11 {
    /// AES128 Key
    #[serde(rename = "appkey", skip_serializing_if = "Option::is_none")]
    pub appkey: Option<String>,
}

impl LoriotInlineObject11 {
    pub fn new() -> LoriotInlineObject11 {
        LoriotInlineObject11 {
            appkey: None,
        }
    }
}


