/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineObject24 {
    /// ignore data from this gateway (for debugging purposes)
    #[serde(rename = "ignore", skip_serializing_if = "Option::is_none")]
    pub ignore: Option<bool>,
    /// custom gateway title updated by user
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Transmission gateway gain
    #[serde(rename = "txgain", skip_serializing_if = "Option::is_none")]
    pub txgain: Option<f32>,
    /// enable / disable alerts for this gateway
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<bool>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<crate::models::LoriotLocation>,
    /// AES key used for gateways LoRaWAN version 2
    #[serde(rename = "aes_key", skip_serializing_if = "Option::is_none")]
    pub aes_key: Option<String>,
    #[serde(rename = "trackFiles", skip_serializing_if = "Option::is_none")]
    pub track_files: Option<crate::models::Loriot1NwkGatewayGweuiTrackFiles>,
}

impl LoriotInlineObject24 {
    pub fn new() -> LoriotInlineObject24 {
        LoriotInlineObject24 {
            ignore: None,
            title: None,
            txgain: None,
            alerts: None,
            location: None,
            aes_key: None,
            track_files: None,
        }
    }
}


