/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotModel {
    /// base / manufacturer of the gateway
    #[serde(rename = "base", skip_serializing_if = "Option::is_none")]
    pub base: Option<String>,
    /// user friendly version of base
    #[serde(rename = "basename", skip_serializing_if = "Option::is_none")]
    pub basename: Option<String>,
    /// Gateway description with HTML formatting
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// TODO
    #[serde(rename = "bus", skip_serializing_if = "Option::is_none")]
    pub bus: Option<Vec<String>>,
    /// TODO
    #[serde(rename = "card", skip_serializing_if = "Option::is_none")]
    pub card: Option<Vec<String>>,
    /// TODO
    #[serde(rename = "concentrator", skip_serializing_if = "Option::is_none")]
    pub concentrator: Option<Vec<String>>,
}

impl LoriotModel {
    pub fn new() -> LoriotModel {
        LoriotModel {
            base: None,
            basename: None,
            description: None,
            bus: None,
            card: None,
            concentrator: None,
        }
    }
}


