/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct Loriot1NwkAppAppidOutputsOsetup {
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<crate::models::Loriot1NwkAppAppidOutputsOsetupRequest>,
}

impl Loriot1NwkAppAppidOutputsOsetup {
    pub fn new() -> Loriot1NwkAppAppidOutputsOsetup {
        Loriot1NwkAppAppidOutputsOsetup {
            request: None,
        }
    }
}


