/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotInlineResponse2002Events {
    /// Log date
    #[serde(rename = "ts", skip_serializing_if = "Option::is_none")]
    pub ts: Option<String>,
    /// Severity enumeration value
    #[serde(rename = "sev", skip_serializing_if = "Option::is_none")]
    pub sev: Option<f32>,
    /// Log event name
    #[serde(rename = "evt", skip_serializing_if = "Option::is_none")]
    pub evt: Option<String>,
    /// Log message
    #[serde(rename = "msg", skip_serializing_if = "Option::is_none")]
    pub msg: Option<String>,
    /// Log metadata properties
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl LoriotInlineResponse2002Events {
    pub fn new() -> LoriotInlineResponse2002Events {
        LoriotInlineResponse2002Events {
            ts: None,
            sev: None,
            evt: None,
            msg: None,
            metadata: None,
        }
    }
}


