/*
 * Public NWK REST API
 *
 * Public LORIOT Network Server NWK REST API documentation
 *
 * The version of the OpenAPI document: 5.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LoriotTier : Tier of the user



#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct LoriotTier {
    /// Informative field for web usage
    #[serde(rename = "applimit", skip_serializing_if = "Option::is_none")]
    pub applimit: Option<String>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Vec<crate::models::LoriotTierFeatures>>,
    /// wellcome message in HTML
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<String>,
    /// type of account
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// numeric value of the tier
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
}

impl LoriotTier {
    /// Tier of the user
    pub fn new() -> LoriotTier {
        LoriotTier {
            applimit: None,
            features: None,
            info: None,
            title: None,
            _id: None,
        }
    }
}


